version: '3'
services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      network: host
    volumes:
      - ./nginx/:/app/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /srv/www/:/srv/www/
    ports:
      - "80:80"
      - "443:443"
